### PR TITLE
fixes for Django 4.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@adamcharnock Could you please look at this and potentially make a new release? Or is there anything I can help with?

**Comment by ge-lem** [comment]
@adamcharnock I think this PR is most wanted. Can you look at it, please ?

**Comment by adamcharnock** [comment]
Thank you for pinging me everyone. Would anyone like to come on as a maintainer and handle this and do the release? Looking particularly at @bashu, but others welcome too.

In absence of any action further pings are welcome.

**Comment by bashu** [comment]
to @adamcharnock to be honest with you, I don't have time right now

**Comment by PetrDlouhy** [comment]
I @adamcharnock I could do that. I could set up GitHub actions and make a new release.

**Comment by adamcharnock** [comment]
Thank you @PetrDlouhy! Invite sent. Also let me know your PyPi username and I can add you.

**Comment by PetrDlouhy** [comment]
My PyPI username is `petr.dlouhy`.

**Comment by PetrDlouhy** [comment]
@adamcharnock I added all the testing, polished the code a bit and prepared everything for release of 1.0.0.
Can you please give mi rights to PyPI?

**Comment by PetrDlouhy** [comment]
@adamcharnock Thank you very much. I have now released the new version.

**Pull request merged**
