### PR TITLE
Preventing updating of a user's last_login field when su'ing

### PR DESCRIPTION
**Pull request by adamcharnock**

### CODE REVIEW

**Comment by adamcharnock** [comment]
@bashu - Unless I hear any objections I'm probably going to merge this in the next few of days.

**Comment by bashu** [comment]
just do it! =)

**Comment by adamcharnock** [comment]
:-) Will do!

**Comment by adamcharnock** [comment]
Just released 0.5.0. Note that I renamed CHANGES -> CHANGES.txt as I generally manage releases with 'seed', and it is (currently) opinionated about some things that perhaps it shouldn't be.

**Pull request merged**
